TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest

plugin/webpay-rest.php
Remove confusing "REST" keyword on payment method name
=> Remove confusing "REST" keyword on payment method name

plugin/src/TransbankWebpayOrders.php
This fix an issue that prevented that the new rest transactions table gets created when the user  had the soap version of the plugin installed before installing this version
Now its gets created automatically
=> Fix database creation error

plugin/src/Helpers/RedirectorHelper.php
Corrección de compatibilidad entre transbank y el plugin timber (motor de plantillas), al momento de ir a la página checkout y tratar de finalizar el pago con el método de pago webpay, retornaba una página en blanco, esto es debido al die que está en la función de redireccionamiento de transbank, debido a que detenía la ejecución de procesos posteriores. Al cambiar este die por un return, el proceso se ejecuta correctamente y sin problemas.
=> Extensión de soporte a temas desarrollados en wordpress con el plugin timber

CHANGELOG.md, plugin/readme.txt
You can see the full diff [here](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/compare/1.2.0...chore/prepare-release-1.3.0)
=> Prepare release 1.3.0

README.md, plugin/readme.txt
You can see the full diff [here](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/compare/1.3.0...chore/prepare-release-1.3.1)
=> Prepare release 1.3.1

plugin/readme.txt
You can see the full diff [here](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/compare/1.3.2...chore/prepare-release-1.3.3)
=> Prepare release 1.3.3

plugin/readme.txt
You can see the full diff [here](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/compare/1.3.3...chore/prepare-release-1.3.4)
=> Prepare release 1.3.4

plugin/js/admin.js
El Plugin jQuery Migrate Helper detecta que los click events estan obsoletos. Para que este plugin ya no aparezca en la lista de plugins desactualizados se ha actualizado.
=> Actualiza deprecated jQuery.fn.click() event 

README.md, plugin/readme.txt, plugin/views/admin/logs.php
= 1.4.0 =
* Se utiliza el nuevo SDk de PHP versión 2.0
* Ya no es compatible con PHP 5.6.
* Ahora es compatible de PHP 7.0 a PHP 8.0
* Ahora se puede completar el formulario de validación directamente desde el plugin
* Se soluciona warning de jQuery [PR 57](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/pull/57)
* Se aplica coding style de StyleCI.
=> Prepare release 1.4.0

plugin/readme.txt
* Ahora el API 1.2 de Transbank a veces redirige por GET al finalizar el flujo y el plugin no funcionaba bien cuando esto pasaba. Ya está arreglado.
=> Prepare release 1.4.1

plugin/composer.lock, plugin/readme.txt, plugin/src/Controllers/OneclickInscriptionResponseController.php, plugin/src/Controllers/ResponseController.php, plugin/src/PaymentGateways/WC_Gateway_Transbank_Oneclick_Mall_REST.php, plugin/views/admin/oneclick-admin-options.php, plugin/webpay-rest.php
Con esta información, podemos ayudar mejor al usuario al momento de querer contratar Oneclick. Podemos saber de manera más simple, si está operando en producción con su propio código de comercio, entonces sabemos que es cliente "stock" y podemos ayudarlo a agilizar su proceso de contratación. 
Al hacer click en el banner de "Contrata acá" llegaría a una URL como esta: 
`https://contrata.transbankdevelopers.cl/?wpcommerce=597035769625&wpenv=TEST&utm_source=woocommerce_plugin&utm_medium=banner&utm_campaign=contrata`
=> Add webpay commerce code and environment to oneclick singup link

.gitignore, .travis.yml, package.sh
Add another zip with a variation of the plugin that uses Guzzle 7 (requires PHP 7.2+). So if someone has an incompatibility issue can manually install this variation, as recommended on some error messages in the plugin.
=> Add guzzle 7 release to github on every release

plugin/readme.txt
Prepare release 1.5.1
You can see the full diff [here](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/compare/1.5.0...1.5.1)
=> Prepare release 1.5.1

plugin/js/admin.js
-  delete unused function reported by sonarcloud
=> fix: delete unused function on plugin/js/admin.js

plugin/css/tbk.css, plugin/js/admin.js, plugin/views/admin/admin-options.php, plugin/views/admin/healthcheck.php, plugin/views/admin/logs.php, plugin/views/admin/oneclick-admin-options.php, plugin/views/admin/phpinfo.php
This PR resolves several sonar cloud bugs associated with the use of tables.
Success:
https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/assets/16402208/af5d2e44-723e-4e9d-86ad-e7d88d5741cf
Error:
https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/assets/16402208/3bb87834-6d22-44d5-a7ae-c326420640e7
=> Fix: sonarcloud admin views bugs

plugin/src/Controllers/ThankYouPageController.php, plugin/webpay-rest.php
This PR resolve a require bug reported by sonarcloud.
Test:
=> fix: replace require by require_once 

plugin/views/order-summary-oneclick.php, plugin/views/order-summary.php
This PR resolve sonarcloud bugs associated to orders summary tables on checkout customer view.
=> fix: add aria-describedby attribute to order summary tables

plugin/css/tbk.css, plugin/js/admin.js, plugin/views/get-status.php
This PR resolves the bugs reported by sonarcloud associated with transaction status table.
**Changelog**
https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/assets/16402208/abb0b4f8-3da4-45ab-ab71-c5c9fb582bcf
=> Fix: sonarcloud status table bugs

plugin/js/admin.js, plugin/src/Controllers/TransactionStatusController.php, plugin/views/get-status.php
This PR resolve an issue in get_status view when transaction was made with oneclick.
Changelog:
https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/assets/16402208/00847961-1aa2-4cab-a3d0-36bf47094da9
=> fix: show get_status view when transaction was made with oneclick 

plugin/views/admin/components/info-validacion-webpay-oneclick-box.php, plugin/views/admin/oneclick-admin-options.php
https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/assets/16402208/cf481642-7f5e-4098-989a-50de79585390
https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/assets/16402208/23ffa75b-5035-4910-9d8e-71e15edf5159
=> fix: remove unused variable $webpayPlusCommerceCode

plugin/src/Controllers/ResponseController.php, plugin/src/Helpers/HposHelper.php, plugin/webpay-rest.php
Add compatibility for hpos since woocommerce 8.2 version. For previous versions it maintains older methods.
Orders data is now stored by woocommerce on tables 
_wc_orders
_wc_order_addresses
_wc_order_operational_data
_wc_orders_meta
=> feat: add hpos compatibility

plugin/src/Models/Transaction.php
This PR fix the flow when the answer for a Webpay Plus transaction is form timeout.
=> fix: webpay timeout response

plugin/src/WebpayplusTransbankSdk.php
This PR fills the environment field on webpay plus transaction table.
Now the environment is correctly displayed in the transaction summary.
=> fix: webpay transaction environment

plugin/views/admin/oneclick-admin-options.php
This PR removes the section to hire the service:
Before:
After:
=> refactor: remove hire section on oneclick settings on woocommerce panel

plugin/src/Helpers/WebpayTransactionsTable.php
This PR resolve warning in transaction view.
before:
after:
=> fix:warnings in transaction view

plugin/src/Controllers/ResponseController.php, plugin/src/Controllers/ThankYouPageController.php, plugin/src/Helpers/InteractsWithFullLog.php
Fixed warning in response controller when order is complete successfully
Before:
Test:
=> fix: warning in response controller

plugin/src/Controllers/OneclickInscriptionResponseController.php, plugin/src/Controllers/ResponseController.php, plugin/src/PaymentGateways/WC_Gateway_Transbank_Oneclick_Mall_REST.php
This PR implements fixes for the webhooks associated with Webpay Plus and Oneclick transactions.
- wc_transbank_webpay_plus_transaction_approved
- wc_transbank_webpay_plus_transaction_failed
- wc_transbank_oneclick_inscription_finished
- wc_transbank_oneclick_inscription_approved
- wc_transbank_oneclick_refund_approved
- wc_transbank_oneclick_refund_failed
- wc_transbank_oneclick_transaction_approved
- wc_transbank_oneclick_transaction_failed
Test
Create Webhook
Webhook activation
=> fix: plugin webhooks

plugin/src/Controllers/OneclickInscriptionResponseController.php, plugin/src/Controllers/ResponseController.php, plugin/src/PaymentGateways/WC_Gateway_Transbank_Oneclick_Mall_REST.php
This PR adds a missing data coming from the method: `get_data()` on the TB Webhooks
=> Fix: woocommerce order data in webhooks

plugin/src/Helpers/MaskData.php
This PR fix the method to mask with pattern, user for buy order and session id.
=> fix: mask pattern method

plugin/src/PaymentGateways/TransbankRESTPaymentGateway.php, plugin/src/PaymentGateways/WC_Gateway_Transbank_Oneclick_Mall_REST.php, plugin/src/PaymentGateways/WC_Gateway_Transbank_Webpay_Plus_REST.php
This PR formats the refund response and removes the JSON response from the note.
Test
=> feat: improve refund response order note

plugin/src/OneclickTransbankSdk.php, plugin/src/TransbankSdk.php, plugin/src/WebpayplusTransbankSdk.php
This PR fix the generation of buy order. 
Now this length must not exceed 26 characters.
=> fix: buy order generation

README.md, plugin/readme.txt
Prepare release 1.7.1 for develop.
Add this changes:
- The format of the refund note for orders has been corrected.
- A bug in the buy order generation has been fixed.
- Removes unnecessary texts.
=> docs: add release notes

plugin/src/PaymentGateways/WC_Gateway_Transbank_Oneclick_Mall_REST.php, plugin/webpay-rest.php
This PR remove a deprecated hook and fix issue https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/issues/226
https://woocommerce.com/document/subscriptions-query-monitor-warning/
No test for this PR :(
=> fix: remove deprecated hook

plugin/webpay-rest.php
This PR add the plugin Woocommerce as a dependency
=> chore: add woocommerce as a dependency

plugin/src/PaymentGateways/WC_Gateway_Transbank_Oneclick_Mall_REST.php
This PR fixes the correct use of methods for payment token filters
=> fix: use correct method in payment token filters

plugin/src/Helpers/MaskData.php
This PR fix a warning message in the class `MaskData`, add protection when input is null in method `mask`.
=> fix: warning when input is null

plugin/shared/Helpers/PluginLogger.php, plugin/templates/admin/log.php
This PR saves in cache only the log file name instead of the log file path.
=> fix: save in cache only log file name

plugin/shared/Helpers/PluginLogger.php
This PR fix the timezone for logs.
=> fix: timezone for logs

.github/workflows/release.yml, plugin/readme.txt, plugin/shared/Helpers/PluginLogger.php, plugin/src/Helpers/MaskData.php, plugin/templates/admin/log.php
Prepare release 1.9.1.
This version includes the following changes:
- Fixed a warning message caused by the maskData function in PHP 8.x and above.
- Fixed an issue that prevented finding the log file when migrating the site from one server to another.
- Fixed the timezone for logs. The timezone configured in the e-commerce site is now used.
- Fixed an issue that caused duplicate entries in the log file selector in the logs view.
=> chore: prepare release 1.9.1

plugin/src/PaymentGateways/WC_Gateway_Transbank_Oneclick_Mall_REST.php
This PR add protections in Oneclick authorization flow.
=> feat: add protections in Oneclick authorization flow

plugin/src/PaymentGateways/WC_Gateway_Transbank_Oneclick_Mall_REST.php, plugin/src/Tokenization/WC_Payment_Token_Oneclick.php
This PR refines the Oneclick authorization flow.
=> feat: use user id instead of the email

plugin/src/PaymentGateways/WC_Gateway_Transbank_Oneclick_Mall_REST.php
This PR set order status when a subscription payment fails.
=> feat: set order status on failed subscription payment

plugin/css/tbk.css, plugin/js/admin.js, plugin/shared/Helpers/PluginLogger.php, plugin/templates/admin/log.php, plugin/webpay-rest.php
This PR add a function to dowload logs from admin view.
=> feat: add download logs function

plugin/css/tbk.css, plugin/js/admin.js, plugin/src/Controllers/TransactionStatusController.php, plugin/src/Helpers/ErrorUtil.php, plugin/src/Helpers/TbkResponseUtil.php, plugin/src/OneclickTransbankSdk.php, plugin/src/WebpayplusTransbankSdk.php, plugin/templates/admin/order/transaction-status.php, plugin/webpay-rest.php
This PR improves the way transaction status data is displayed. The detail is:
- Improve messages to users.
- Add formatting to fields.
- Add logs to the controller to obtain the status of the transaction.
- Improves error control.
Note: 
The colors in the status were added so that the transaction can always be consulted in the future, if possible, not only when it is approved.
=> feat: improve information for transaction status

plugin/js/admin.js
This PR add a color class for the reversed state in the status meta box.
=> feat: add color class for reversed state

plugin/src/Controllers/TransactionStatusController.php, plugin/templates/admin/order/transaction-status.php
This PR resolves an issue where the "Check Status" button was displayed even when no Webpay transaction was present.
=> fix: show meta box status when no transaction found

plugin/src/Utils/ConnectionCheck.php
This PR rename the test connection method to improve legilibility.
=> refactor: rename test connection method

plugin/src/Helpers/WebpayTransactionsTable.php
This PR improve the information in the transaction table.
- Remove redundant fields.
- Improve columns names
- Add link to Woocommerce order.
=> feat: improve transaction table

plugin/webpay-rest.php
This PR remove a deprecated message from ecommerce site when use the Webpay Plus config options in WooCommerce menu.
=> fix: deprecated warning message
