CHANGELOG.md, plugin/webpay-rest.php
Change some function names to avoid duplicated code with SOAP plugin
=> Change some function names to avoid duplicated code with SOAP plugin

CHANGELOG.md
You can see the full diff [here](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay/compare/0.0.1...chore/prepare-release-1.0.0)
=> Prepare release 1.0.0

plugin/webpay-rest.php
=> Fix typo en environment

plugin/webpay-rest.php
Add message when currency is not clp
=> Add message when currency is not clp

plugin/composer.json, plugin/composer.lock, plugin/src/Controllers/ResponseController.php, plugin/views/order-summary.php, plugin/webpay-rest.php
Fix order details and installments number on confirmation page
=> Fix order details and installments number

plugin/src/Controllers/ResponseController.php, plugin/webpay-rest.php
Add automatic refund
Se agrega la opción de refund con Transbank
Luego de hacer refund queda así en la lista de ordenes
=> Add automatic refund

plugin/composer.lock
=> Update SDK to 1.10

plugin/webpay-rest.php
=> Add webpay plus menu under woocommerce menu

.travis.yml
=> Fix Github Api Key

plugin/composer.json, plugin/composer.lock
=> Update PHP SDK to 1.10.1

plugin/css/tbk.css, plugin/src/Helpers/HealthCheck.php, plugin/views/admin/healthcheck.php
Fix check connection on production environment
Before, when you test your connection on production environment you get this: 
Now it is fixed:
=> Fix check connection on production environment

plugin/readme.txt
You can see the full diff [here](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/compare/1.3.1...chore/prepare-release-1.3.2)
=> Prepare release 1.3.2

plugin/views/order-summary.php
Pequeña corrección ortográfica. Según mi esposa profesora la palabra es: (de la ) osea separada con un espacio.
=> Corrección ortográfica

plugin/readme.txt
=> Add support to Wordpress 5.6

plugin/css/tbk.css, plugin/src/Controllers/ResponseController.php
Improve order notes on successful transaction
=> Improve order notes on successful transaction

plugin/src/Controllers/ResponseController.php
Fix incompatibility with older versions of PHP
=> Fix incompatibility with older versions of PHP

plugin/src/Telemetry/PluginVersion.php
Make the plugin to not depend strictly on Soap
=> Make the plugin to not depend strictly on Soap

plugin/composer.json, plugin/composer.lock, plugin/src/Helpers/ConfigProvider.php, plugin/src/Helpers/HealthCheck.php, plugin/src/TransbankSdkWebpayRest.php, plugin/views/admin/healthcheck.php, plugin/webpay-rest.php
=> Update SDK to 2.0-beta

plugin/css/tbk.css, plugin/views/admin/admin-options.php, plugin/views/admin/logs.php
=> Add typeform

plugin/composer.json, plugin/src/Controllers/ResponseController.php, plugin/views/admin/logs.php, plugin/webpay-rest.php
As this uses the API 1.2, the request sometimes comes from a GET request.
=> Get data from get or post

plugin/src/Helpers/LogHandler.php, plugin/views/admin/logs.php
=> Improve logs preview

plugin/src/Helpers/HealthCheck.php, plugin/src/Helpers/WebpayTransactionsTable.php, plugin/views/admin/options-tabs.php, plugin/views/admin/transactions.php, plugin/webpay-rest.php
=> Add transactions view

plugin/src/Helpers/ErrorHelper.php, plugin/src/PaymentGateways/WC_Gateway_Transbank_Oneclick_Mall_REST.php, plugin/webpay-rest.php
=> Improve error handling of guzzle incompatibility with other plugins

plugin/src/Controllers/ResponseController.php, plugin/src/Controllers/ThankYouPageController.php
Fix time of transaction using UTC time from wordpress
=> Fix time of transaction using UTC time from wordpress

plugin/readme.txt, plugin/webpay-rest.php
You can see the full diff [here](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/compare/1.4.1...1.5.0)
=> Prepare release 1.5.0

plugin/src/Controllers/ResponseController.php, plugin/src/Helpers/PluginInfoHelper.php, plugin/src/PaymentGateways/TransbankRESTPaymentGateway.php, plugin/src/PaymentGateways/WC_Gateway_Transbank_Oneclick_Mall_REST.php, plugin/views/admin/admin-options.php, plugin/views/admin/oneclick-admin-options.php, plugin/webpay-rest.php
=> Add more hooks

plugin/readme.txt, plugin/src/Controllers/OneclickInscriptionResponseController.php, plugin/src/PaymentGateways/WC_Gateway_Transbank_Oneclick_Mall_REST.php
You can see the full diff [here](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/compare/1.5.1...1.5.2)
=> Prepare release 1.5.2

plugin/src/Controllers/ResponseController.php
Also fix response code checking
=> Add prepaid payment type code

plugin/readme.txt
full diff : https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/compare/1.6.0...master
=> fix monolog error

plugin/readme.txt
full diff: https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/compare/1.6.1...master
=> add 6.1.2 changelog

plugin/readme.txt
full diff: https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/compare/1.6.2...master
=> add 1.6.3 changelog

plugin/readme.txt, plugin/src/Controllers/ResponseController.php, plugin/src/Helpers/InteractsWithFullLog.php, plugin/src/TransbankSdkWebpayRest.php, plugin/webpay-rest.php
[Full Diff...](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/compare/chore/prepare-release-1.6.4)
=> Prepare Release 1.6.4

plugin/src/PaymentGateways/WC_Gateway_Transbank_Oneclick_Mall_REST.php, plugin/src/Telemetry/PluginVersion.php, plugin/webpay-rest.php
- Added function to store information about the plugin and the commerce when saving plugin settings.
=> Add Woocommerce Metrics

plugin/readme.txt
[Full Diff...](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/compare/1.6.4...master)
=> Prepare Release 1.6.5

plugin/webpay-rest.php
=> fix reference version

plugin/readme.txt, plugin/webpay-rest.php
full diff: https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/compare/1.6.5...master?expand=1
=> Chore/prepare release 1.6.6

plugin/src/Helpers/WebpayTransactionsTable.php
Santize sql query on transaction table due risk to sql injection.
=> Fix: sanitize sql query on transaction table

plugin/readme.txt
Add changelog to release new version
=> Add 1.6.7 changelog

plugin/src/PaymentGateways/WC_Gateway_Transbank_Oneclick_Mall_REST.php, plugin/views/admin/admin-options.php, plugin/views/admin/oneclick-admin-options.php, plugin/views/admin/options-tabs.php, plugin/webpay-rest.php
* replace include with include_once
=> replace include with include_once recommended by sonar

plugin/src/Helpers/WebpayTransactionsTable.php, plugin/src/PaymentGateways/WC_Gateway_Transbank_Webpay_Plus_REST.php
* improve order refund method
* new column
* refund error
* refund ok
=> feat: improve order refund method

plugin/css/tbk.css, plugin/js/admin.js, plugin/src/Controllers/TransactionStatusController.php, plugin/src/Models/Transaction.php, plugin/views/get-status.php
* improve order status method
* Status OK
* Status Error
=> feat: improve order status method

README.md
=> docs: add general standards for commits and branches

plugin/composer.json, plugin/shared/Exceptions/EcommerceException.php, plugin/shared/Helpers/ArrayUtils.php, plugin/shared/Helpers/DateUtils.php, plugin/shared/Helpers/ExceptionConstants.php, plugin/shared/Helpers/GitHubUtil.php, plugin/shared/Helpers/ILogger.php, plugin/shared/Helpers/InfoUtil.php, plugin/shared/Helpers/ObjectUtil.php, plugin/shared/Helpers/PluginLogger.php, plugin/shared/Helpers/StringUtils.php, plugin/shared/Helpers/TbkConstants.php, plugin/shared/Helpers/TbkDatabaseConstants.php, plugin/shared/Helpers/TbkValidationUtil.php, plugin/shared/Helpers/WoocommerceInfoUtil.php, plugin/shared/Model/LogConfig.php, plugin/shared/Model/OneclickConfig.php, plugin/shared/Model/ProductConfig.php, plugin/shared/Model/WebpayplusConfig.php
* new utilities added to correct errors reported by kiuwan
=> feat: add shared utilities

docker-woocommerce-php7.4-wp6.0.0-wc2.6.0-woo6.0.0/README.md, docker-woocommerce-php7.4-wp6.0.0-wc2.6.0-woo6.0.0/docker-compose.yml, docker-woocommerce-php7.4-wp6.0.0-wc2.6.0-woo6.5.0/README.md, docker-woocommerce-php7.4-wp6.0.0-wc2.6.0-woo6.5.0/docker-compose.yml, docker-woocommerce-php8.2-wp6.4.1-wc2.9.0-woo8.1.0/README.md, docker-woocommerce-php8.2-wp6.4.1-wc2.9.0-woo8.1.0/docker-compose.yml, docker-woocommerce-php8.2-wp6.4.1-wc2.9.0-woo8.2.0/README.md, docker-woocommerce-php8.2-wp6.4.1-wc2.9.0-woo8.2.0/docker-compose.yml, docker-woocommerce-php8.2-wp6.4.1-wc2.9.0-woo8.3.0/README.md, docker-woocommerce-php8.2-wp6.4.1-wc2.9.0-woo8.3.0/docker-compose.yml
* add docker compose files for test
=> chore: add docker for test

docker-woocommerce-php8.2-wp6.4.1-wc2.9.0-woo8.5.0/README.md, docker-woocommerce-php8.2-wp6.4.1-wc2.9.0-woo8.5.0/docker-compose.yml
- add docker files for wocommerce 8.5.0 and php 8.2
=> chore: add docker php8.2 woocommerce8.5.0

plugin/shared/Helpers/PluginLogger.php, plugin/src/Helpers/TbkFactory.php, plugin/views/admin/logs.php
=> feat: improve logs handling

plugin/js/admin.js, plugin/shared/Helpers/WoocommerceInfoUtil.php, plugin/src/Controllers/OneclickInscriptionResponseController.php, plugin/src/Controllers/ResponseController.php, plugin/src/Controllers/TransactionStatusController.php, plugin/src/Helpers/ConfigProvider.php, plugin/src/Helpers/PluginInfoHelper.php, plugin/src/Helpers/WebpayTransactionsTable.php, plugin/src/Models/BaseModel.php, plugin/src/Models/Inscription.php, plugin/src/Models/Transaction.php, plugin/src/Models/TransbankApiServiceLog.php, plugin/src/Models/TransbankExecutionErrorLog.php, plugin/src/PaymentGateways/WC_Gateway_Transbank_Oneclick_Mall_REST.php, plugin/src/PaymentGateways/WC_Gateway_Transbank_Webpay_Plus_REST.php, plugin/src/TransbankSdk.php, plugin/views/admin/admin-options.php, plugin/views/admin/healthcheck.php, plugin/views/admin/logs.php, plugin/views/admin/oneclick-admin-options.php, plugin/views/admin/options-tabs.php, plugin/views/get-status.php, plugin/views/order-summary-oneclick.php, plugin/views/order-summary.php, plugin/webpay-rest.php
* fix multiples kiuwan bugs:
** remove unnecessary exit
** remove unused references
** factorize javascript for check status, tables, api
** factorize model classes
** fix register_activation_hook
=> fix : kiuwan bugs 3

plugin/js/admin.js, plugin/src/PaymentGateways/WC_Gateway_Transbank_Oneclick_Mall_REST.php, plugin/src/PaymentGateways/WC_Gateway_Transbank_Webpay_Plus_REST.php, plugin/src/Utils/TableCheck.php, plugin/views/admin/logs.php, plugin/webpay-rest.php
* fix multiples kiuwan bugs:
* * replace exception to throwable class
** replace throw Exception to EcommerceException
** save html in a variable beforehand
=> fix: kiuwan bugs

plugin/readme.txt, plugin/webpay-rest.php
PR for release 1.7.0. to develop
This release includes the following changes:
* The operation of the webhooks implemented for third-party development is corrected
* Sensitive data is obfuscated in the log when the environment is production.
* Improvements are made in log handling.
* Compatibility with block checkout is added.
* Compatibility with HPOS is added.
* The service for collecting plugin data is removed.
* The status query through Oneclick is corrected.
* Operation states are recorded in the database.
* Error columns are added to the transaction view.
* Security enhancements are added.
* Minor bug fixes are made.
=> chore: prepare release 1.7.0

plugin/views/admin/admin-options.php, plugin/views/admin/components/info-validacion-webpay-oneclick-box.php, plugin/views/admin/oneclick-admin-options.php
This PR removes unnecessary text references.
Before:
After:
Before:
After:
=> refactor: remove unnecessary text

README.md, plugin/readme.txt, plugin/src/OneclickTransbankSdk.php, plugin/src/PaymentGateways/TransbankRESTPaymentGateway.php, plugin/src/PaymentGateways/WC_Gateway_Transbank_Oneclick_Mall_REST.php, plugin/src/PaymentGateways/WC_Gateway_Transbank_Webpay_Plus_REST.php, plugin/src/TransbankSdk.php, plugin/src/WebpayplusTransbankSdk.php, plugin/views/admin/admin-options.php, plugin/views/admin/components/info-validacion-webpay-oneclick-box.php, plugin/views/admin/oneclick-admin-options.php
Prepare release 1.7.1.
Add this changes:
- The format of the refund note for orders has been corrected.
- A bug in the buy order generation has been fixed.
- Removes unnecessary texts.
=> chore: prepare release 1.7.1

plugin/src/Controllers/ResponseController.php, plugin/src/Controllers/TransactionStatusController.php, plugin/src/Helpers/TbkResponseUtil.php, plugin/src/Helpers/WebpayTransactionsTable.php, plugin/src/PaymentGateways/TransbankRESTPaymentGateway.php, plugin/src/PaymentGateways/WC_Gateway_Transbank_Oneclick_Mall_REST.php
This PR formats the transactions date to display it as local date.
Partial refund note: 
Order note
Transaction list
Transaction status
=> feat: format to local date

plugin/css/tbk.css, plugin/views/admin/logs.php
This PR format the log content in view logs
[transbank-webpay-plus-rest-guzzle7.zip](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/files/14420560/transbank-webpay-plus-rest-guzzle7.zip)
[transbank-webpay-plus-rest.zip](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/files/14420561/transbank-webpay-plus-rest.zip)
=> feat: improve log view

plugin/css/tbk.css, plugin/src/PaymentGateways/WC_Gateway_Transbank_Oneclick_Mall_REST.php, plugin/src/PaymentGateways/WC_Gateway_Transbank_Webpay_Plus_REST.php
This PR allow edit payment gateways descriptions.
[transbank-webpay-plus-rest-guzzle7.zip](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/files/14435509/transbank-webpay-plus-rest-guzzle7.zip)
[transbank-webpay-plus-rest.zip](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/files/14435510/transbank-webpay-plus-rest.zip)
=> feat: add edit payment gateways description

plugin/src/PaymentGateways/WC_Gateway_Transbank_Oneclick_Mall_REST.php, plugin/src/PaymentGateways/WC_Gateway_Transbank_Webpay_Plus_REST.php
This PR change api key field to password type in admin view.
[transbank-webpay-plus-rest-guzzle7.zip](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/files/14439348/transbank-webpay-plus-rest-guzzle7.zip)
[transbank-webpay-plus-rest.zip](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/files/14439350/transbank-webpay-plus-rest.zip)
=> feat: change api key field to password type

plugin/css/tbk.css, plugin/js/admin.js, plugin/src/Helpers/NoticeHelper.php, plugin/templates/public/notices/review-notice.php, plugin/webpay-rest.php
This PR add a review notice in the plugin admin panel
Test
=> feat: add review notice

plugin/src/Controllers/ThankYouPageController.php
This PR resolve kiuwan issues
Test
=> fix: kiuwan issues

plugin/readme.txt
=> Chore/prepare release 1.8.0

plugin/css/tbk.css, plugin/src/Controllers/LogController.php, plugin/templates/admin/log.php, plugin/views/admin/options-tabs.php
This PR adds functionality to select the log file in log view.
=> feat: allow select log file

plugin/src/PaymentGateways/WC_Gateway_Transbank_Oneclick_Mall_REST.php
This PR fix exception when processing a rejected subscription.
No test for subscriptions :(
=> fix: exception when processing rejected subscription

plugin/src/PaymentGateways/WC_Gateway_Transbank_Oneclick_Mall_REST.php
This PR improve authorization flow for Oneclick payment.
=> refactor: improve authorize flow for Oneclick

plugin/src/PaymentGateways/WC_Gateway_Transbank_Oneclick_Mall_REST.php
This PR replaces the direct use of the $_POST variable and sanitize the payment token data.
=> fix: kiuwan report

plugin/readme.txt, plugin/webpay-rest.php
=> chore: prepare release 1.9.0 to develop

.github/workflows/release.yml
This PR fix a problem in release action.
No test for actions 😢
=> chore: separate asset uploads

plugin/src/Controllers/ResponseController.php, plugin/src/Helpers/TransactionResponseHandler.php, plugin/src/WebpayplusTransbankSdk.php
- Moved flow detection and protection logic from the SDK class to a new class.
- Fixed all Sonar comments from the previous PR #250
=> refactor: restructure code flow

plugin/src/Helpers/WebpayTransactionsTable.php
This PR refine transaction fetch flow for transaction view.
=> feat: improve transaction fetch flow

plugin/composer.json, plugin/shared/Helpers/InfoUtil.php, plugin/src/Controllers/TransactionStatusController.php, plugin/webpay-rest.php
This PR add support for PHP 8.2.
=> feat: support php 8.2

plugin/composer.json, plugin/shared/Helpers/InfoUtil.php
This PR revert support for PHP 8.2.
=> revert: support for php 8.2

plugin/readme.txt
=> chore: prepare release 1.9.2

plugin/readme.txt, plugin/src/PaymentGateways/WC_Gateway_Transbank_Oneclick_Mall_REST.php
Release for version 1.9.3
Full Diff: https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/compare/master...chore/prepare-release-1.9.3
=> Prepare release 1.9.3

plugin/css/tbk.css
=> refactor: remove unused css

plugin/composer.json
This PR update the Transbank SDK and the PHP version.
=> chore: update dependencies

.github/workflows/release.yml, package.sh
This PR removes the creation of the guzzle7 zip.
=> chore: remove zip guzzle7 creation

plugin/js/admin.js
This PR resolve kiuwan report.
=> fix: reduce nested callbacks

README.md, plugin/readme.txt, plugin/webpay-rest.php
=> chore: prepare release 1.10.0

plugin/composer.json
This PR update the dependency monolog.
=> chore: update monolog dependency

plugin/shared/Exceptions/BaseException.php, plugin/src/PaymentGateways/WC_Gateway_Transbank_Webpay_Plus_REST.php
This PR refine the exception base.
=> feat: refine base exception

plugin/src/Blocks/js/notice_handler.js, plugin/src/Helpers/TransactionResponseHandler.php
This PR refine the Webpay payment flow.
=> feat: refine payment flow

plugin/src/PaymentGateways/WC_Gateway_Transbank_Oneclick_Mall_REST.php, plugin/src/PaymentGateways/WC_Gateway_Transbank_Webpay_Plus_REST.php
This PR improve the payment activation option for Webpay Plus and Webpay Oneclick.
=> feat: improve product activation option

plugin/css/tbk.css, plugin/js/admin.js, plugin/package.json, plugin/src/Helpers/BuyOrderHelper.php, plugin/src/Helpers/MaskData.php, plugin/src/Helpers/TbkFactory.php, plugin/src/OneclickTransbankSdk.php, plugin/src/PaymentGateways/WC_Gateway_Transbank_Oneclick_Mall_REST.php, plugin/src/PaymentGateways/WC_Gateway_Transbank_Webpay_Plus_REST.php, plugin/src/TransbankSdk.php, plugin/src/WebpayplusTransbankSdk.php
* add buy order format config to Webpay
* add buy order format config to Oneclick
https://github.com/user-attachments/assets/4e6a0133-17ce-42ce-8c0e-f1e4cb57af3c
=> feat: add buy order format

plugin/package.json
This PR updates JavaScript dependencies.
=> chore: update javascript dependencies

plugin/src/Blocks/js/notice_handler.js, plugin/src/Models/Transaction.php
This PR resolve the Kiuwan Alerts.
=> fix: kiuwan alerts

plugin/composer.json, plugin/css/tbk.css, plugin/js/admin.js, plugin/package.json, plugin/readme.txt, plugin/shared/Exceptions/BaseException.php, plugin/src/Blocks/js/notice_handler.js, plugin/src/Controllers/TransactionStatusController.php, plugin/src/Helpers/BuyOrderHelper.php, plugin/src/Helpers/MaskData.php, plugin/src/Helpers/TbkFactory.php, plugin/src/Helpers/TransactionResponseHandler.php, plugin/src/Helpers/WebpayTransactionsTable.php, plugin/src/Models/Transaction.php, plugin/src/OneclickTransbankSdk.php, plugin/src/PaymentGateways/WC_Gateway_Transbank_Oneclick_Mall_REST.php, plugin/src/PaymentGateways/WC_Gateway_Transbank_Webpay_Plus_REST.php, plugin/src/TransbankSdk.php, plugin/src/WebpayplusTransbankSdk.php, plugin/webpay-rest.php
Release version 1.11.0
Full Diff: https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/compare/1.10.0...develop
=> chore: prepare release 1.11.0

plugin/composer.json, plugin/readme.txt, plugin/shared/Helpers/InfoUtil.php, plugin/src/OneclickTransbankSdk.php, plugin/src/PaymentGateways/WC_Gateway_Transbank_Webpay_Plus_REST.php, plugin/src/WebpayplusTransbankSdk.php
This PR update the dependencies to create the plugin.
- Update Transbank SDK.
- Update Log library.
- Update minimum PHP version.
- Implement the new SDK credential methods.
=> chore: update php dependencies

plugin/shared/Exceptions/RecordNotFoundOnDatabaseException.php, plugin/shared/Model/OneclickConfig.php, plugin/shared/Model/ProductConfig.php, plugin/shared/Repositories/InscriptionRepositoryInterface.php, plugin/shared/Repositories/TransactionRepositoryInterface.php, plugin/shared/Repositories/TransbankApiServiceLogRepositoryInterface.php, plugin/shared/Repositories/TransbankExecutionErrorLogRepositoryInterface.php, plugin/src/Controllers/OneclickInscriptionResponseController.php, plugin/src/Controllers/ResponseController.php, plugin/src/Controllers/ThankYouPageController.php, plugin/src/Controllers/TransactionStatusController.php, plugin/src/Helpers/DatabaseTableInstaller.php, plugin/src/Helpers/TbkFactory.php, plugin/src/Helpers/TransactionResponseHandler.php, plugin/src/Models/Inscription.php, plugin/src/Models/Transaction.php, plugin/src/OneclickTransbankSdk.php, plugin/src/Repositories/InscriptionRepository.php, plugin/src/Repositories/TransactionRepository.php, plugin/src/Repositories/TransbankApiServiceLogRepository.php, plugin/src/Repositories/TransbankExecutionErrorLogRepository.php, plugin/src/TransbankSdk.php, plugin/src/Utils/TableCheck.php, plugin/src/WebpayplusTransbankSdk.php, plugin/webpay-rest.php
* add pattern repository - the repository pattern has been introduced to facilitate the creation of tests.
=> feat: add repository pattern

plugin/src/OneclickTransbankSdk.php
This PR fix the constant name for oneclick sdk file.
=> fix: constant name

plugin/src/Helpers/TbkResponseUtil.php
This PR improve the status flow and the response fields parsing.
=> feat: improve field parsing in tbk response util

plugin/shared/Helpers/TbkConstants.php, plugin/src/Exceptions/CreateTableException.php, plugin/src/Helpers/DatabaseTableInstaller.php, plugin/webpay-rest.php
This PR improves logic to install tables on db and handle errors
Installation ok:
Error:
=> refactor: database installer

plugin/src/Services/OneclickAuthorizationService.php
This PR fix authorization service errors.
before:
now:
=> fix: authorization service
